### ISSUE TITLE
400 error: "Max date range is  100 days"

### ISSUE THREAD

**Issue by andrewjbennett** [carrotflakes/fitbit-sleep-vis#1]
When I try to load the page, it gives me an "error 400".

Looking at the network requests, it's trying to load this page: 
https://api.fitbit.com/1.2/user/-/sleep/date/2023-02-17/2023-05-29.json

which gives this error:

```
{"errors":[{"errorType":"validation","fieldName":"endDate","message":"Max date range is  100 days"}]}
```

There are 101 days between 2023-02-17 and 2023-05-29.

Are you able to decrease it so it tries to only access e.g. 90 days at a time?

**Comment by carrotflakes** [comment]
@andrewjbennett 
Thank you for reporting the issue.

This bug is weird because the code is calculating exactly 100 days ago.
It's possible to shorten the range, but I'd like to find out the cause first.

Could you please let me know which browser you are using? Also, does this issue occur on other days as well?

**Comment by andrewjbennett** [comment]
I can reproduce the problem in Chrome and Firefox, both on my Linux desktop
and Android phone.

I'll try it again tomorrow and see whether the problem persists.

PS: I got it running locally and edited the range to be 90 at a time rather
than 100 (and can confirm that the problem is just with the range being too
large, not anything else) - now that I've had a chance to use it, I think
your app is extremely cool and useful, thanks for making it :)

**Comment by carrotflakes** [comment]
@andrewjbennett 
Thank you for providing detailed information. I'm glad you like my app!:smile_cat: 

I noticed the possibility of time discrepancies due to daylight saving time and made adjustments to the code (I changed the time zone in my environment and tested it). I believe this should have resolved the bug without reducing the range. Please give it a try and let me know.

**Comment by andrewjbennett** [comment]
It's working for me now! Thanks for the quick fix :)

**Comment by carrotflakes** [comment]
I'm glad to hear that it worked! Thank you for your cooperation in improving the app :)

**Comment by blackle** [comment]
@carrotflakes hey there! Seems this problem is happening again today while making this request: `https://api.fitbit.com/1.2/user/-/sleep/date/2024-12-23/2025-04-02.json`

I am in the Toronto time zone, if that helps. I cloned the repo and reduced the number of days to fetch to 90, and it seems like it works after doing so.

**Comment by carrotflakes** [comment]
@blackle 
Thank you for your report!

I was able to reproduce the same issue on my end.
There might have been an update to the date validation in the API, though I’m not entirely sure...
As a temporary measure, I’ve adjusted the number of days retrieved by reducing it by one.

Could you please check if it works now?

**Comment by blackle** [comment]
@carrotflakes sorry only seeing this now. Just fetched/rebased and it works for me! It might be some weird business with the specific day of the year.

BTW thank you so much for making this app. I have a peculiar kind of sleep disorder and this app really helps me see patterns in what's happening. Good work!

**Comment by carrotflakes** [comment]
@blackle 

Glad it’s working!

Yeah, it’s weird — even though the date ranges cover the same length, the results are different:

`2024-12-23/2025-04-02.json`
`2024-12-26/2025-04-05.json`

It's probably a bug in the API.
I’ll stick with the current logic for now, since it’s more stable anyway. (The old one was actually pulling 101 days, which wasn’t quite right.)

Super glad to hear the app’s been helpful for you — that really means a lot☺️
